modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="clockwork"
version="1.0.0"
displayName="Clockwork"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="GÖKALP, MCreator"

[[dependencies.clockwork]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




